# Generated by Django 5.1.3 on 2025-05-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wordle", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="word",
            old_name="word",
            new_name="text",
        ),
    ]
