# Generated by Django 5.2.2 on 2025-06-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordle", "0002_rename_word_word_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40)),
                ("status", models.CharField(max_length=20)),
                ("target_word", models.CharField(max_length=5)),
                ("guesses", models.JSONField(default=list)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
            ],
            options={
                "unique_together": {("session_key",)},
            },
        ),
    ]
