# Generated by Django 5.2.2 on 2025-06-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordle", "0003_game"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="target_word",
            new_name="winning_word",
        ),
        migrations.AddField(
            model_name="game",
            name="game_over",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="won",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="game",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
