# Generated by Django 5.2.2 on 2025-06-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0005_alter_game_options_alter_game_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
    ]
