# Generated by Django 5.2.2 on 2025-07-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0006_remove_game_session_key_remove_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='statuses',
            field=models.JSONField(default=list),
        ),
    ]
